<?xml version="1.0"?>
<robot name="qm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="robot_type" default="aliengo"/>

    <xacro:include filename="$(find qm_description)/urdf/quadruped/common/materials.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/quadruped/common/leg.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/quadruped_manipulator/gazebo.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/quadruped/common/imu.xacro"/> 
    <xacro:include filename="$(find qm_description)/urdf/quadruped/aliengo/const.xacro"/>  
    <xacro:include filename="$(find qm_description)/urdf/quadruped_manipulator/const.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/manipulator/const.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/manipulator/transmission.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/quadruped_manipulator/camera.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/quadruped_manipulator/camera2.xacro"/>
    <xacro:include filename="$(find qm_description)/urdf/manipulator/ft_sensor.xacro"/>

    <xacro:arg name="UnitreeGripper" default="true"/>

  <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
    <xacro:if value="$(arg DEBUG)">
        <link name="world"/>
        <joint name="base_static_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="base"/>
        </joint>
    </xacro:if> 

     <!-- Aliengo robot -->
     <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/quadruped/$(arg robot_type)/trunk.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${trunk_length} ${trunk_width} ${trunk_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                    ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                    iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                    izz="${trunk_izz}"/>
        </inertial>
    </link>

    <!-- D435 IntelRealSense Camera -->
    <xacro:sensor_d435 parent="base" name="camera2" use_nominal_extrinsics="true">
        <origin xyz="0.32 0.01 -0.035" rpy="0 0 0"/>
    </xacro:sensor_d435>

    <!-- IMU -->
    <xacro:IMU connected_to="base" imu_name="unitree_imu" xyz="0. 0. 0." rpy="0. 0. 0."/>

    <!-- Aliengo legs -->
    <xacro:leg prefix="RF" mirror="-1" mirror_dae="False" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg prefix="LF" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg prefix="RH" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg prefix="LH" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <!-- Z1 manipulator -->
    <joint name="manipulator_joint" type="fixed">
        <origin rpy="${arm_offset_r} ${arm_offset_p} ${arm_offset_yaw}" xyz="${arm_offset_x} ${arm_offset_y} ${arm_offset_z}"/>
        <parent link="base"/>
        <child link="z1_link_0"/>
    </joint> 

    <link name="z1_link_0">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/manipulator/z1_Link00.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${motor_height}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${motor_height/2.0}"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${L00_ComX} ${L00_ComY} ${L00_ComZ}"/>
            <mass value="${L00_Mass}"/>
            <inertia
                ixx="${L00_Ixx}" ixy="${L00_Ixy}" ixz="${L00_Ixz}"
                iyy="${L00_Iyy}" iyz="${L00_Iyz}"
                izz="${L00_Izz}"/>  
        </inertial>
    </link> 

   <joint name="z1_joint_1" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0.0585"/>
        <parent link="z1_link_0"/>
        <child link="z1_link_1"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
        <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${joint1_PositionMin}" upper="${joint1_PositionMax}"/>
    </joint>

    <xacro:motorTransmission name="1"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_1_ft_sensor_topic</topicName>
        <jointName>z1_joint_1</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_1">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                 <mesh filename="package://qm_description/meshes/manipulator/z1_Link01.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${2*motor_height}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision> 
        <inertial>
            <origin rpy="0 0 0" xyz="${L01_ComX} ${L01_ComY} ${L01_ComZ}"/>
            <mass value="${L01_Mass}"/>
            <inertia
                ixx="${L01_Ixx}" ixy="${L01_Ixy}" ixz="${L01_Ixz}"
                iyy="${L01_Iyy}" iyz="${L01_Iyz}"
                izz="${L01_Izz}"/>  
        </inertial>
    </link>

    <joint name="z1_joint_2" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0.045"/>
        <parent link="z1_link_1"/>
        <child link="z1_link_2"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${2*jointDamping}" friction="${2*jointFriction}"/>
        <limit effort="${2*torqueMax}" velocity="${velocityMax}" lower="${joint2_PositionMin}" upper="${joint2_PositionMax}"/>
    </joint>
    
    <xacro:motorTransmission name="2"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_2_ft_sensor_topic</topicName>
        <jointName>z1_joint_2</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_2">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/manipulator/z1_Link02.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${2.0*motor_height}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/>
        </collision>
        <collision>
            <geometry>
                <cylinder length="${arm1_height}" radius="${arm1_diameter}"/>
            </geometry>
            <origin rpy="0 ${PI/2.0} 0" xyz="${-0.045-arm1_height/2.0} 0 0"/>
        </collision>
        <collision>
            <geometry>
                <cylinder length="${motor_height}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="${PI/2.0} 0 0" xyz="-0.35 0 0"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${L02_ComX} ${L02_ComY} ${L02_ComZ}"/>
            <mass value="${L02_Mass}"/>
            <inertia
                ixx="${L02_Ixx}" ixy="${L02_Ixy}" ixz="${L02_Ixz}"
                iyy="${L02_Iyy}" iyz="${L02_Iyz}"
                izz="${L02_Izz}"/>  
        </inertial>
    </link>
 
    <joint name="z1_joint_3" type="revolute">
        <origin rpy="0 0 0" xyz="-0.35 0 0"/>
        <parent link="z1_link_2"/>
        <child link="z1_link_3"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
        <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${joint3_PositionMin}" upper="${joint3_PositionMax}"/>
    </joint>

    <xacro:motorTransmission name="3"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_3_ft_sensor_topic</topicName>
        <jointName>z1_joint_3</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_3">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/manipulator/z1_Link03.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${arm2_height-0.01}" radius="${arm2_diameter}"/>
            </geometry>
            <origin rpy="0 ${PI/2.0} 0" xyz="${0.065+arm2_height/2.0} 0 0.055"/>
        </collision>
        <collision>
            <geometry>
                <cylinder length="0.059" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="0 ${PI/2.0} ${PI/2.0}" xyz="${0.065+0.185-0.059/2.0} 0 0.055"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${L03_ComX} ${L03_ComY} ${L03_ComZ}"/>
            <mass value="${L03_Mass}"/>
            <inertia
                ixx="${L03_Ixx}" ixy="${L03_Ixy}" ixz="${L03_Ixz}"
                iyy="${L03_Iyy}" iyz="${L03_Iyz}"
                izz="${L03_Izz}"/>  
        </inertial>
    </link>

    <joint name="z1_joint_4" type="revolute">
        <origin rpy="0 0 0" xyz="0.218 0 0.057"/>
        <parent link="z1_link_3"/>
        <child link="z1_link_4"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
        <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${joint4_PositionMin}" upper="${joint4_PositionMax}"/>
    </joint>

    <xacro:motorTransmission name="4"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_4_ft_sensor_topic</topicName>
        <jointName>z1_joint_4</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_4">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                 <mesh filename="package://qm_description/meshes/manipulator/z1_Link04.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${motor_height + 2*0.008}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0.072 0 0"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${L04_ComX} ${L04_ComY} ${L04_ComZ}"/>
            <mass value="${L04_Mass}"/>
            <inertia
                ixx="${L04_Ixx}" ixy="${L04_Ixy}" ixz="${L04_Ixz}"
                iyy="${L04_Iyy}" iyz="${L04_Iyz}"
                izz="${L04_Izz}"/>  
        </inertial>
    </link>

    <joint name="z1_joint_5" type="revolute">
        <origin rpy="0 0 0" xyz="0.07 0.0 0.0"/>
        <parent link="z1_link_4"/>
        <child link="z1_link_5"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
        <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${joint5_PositionMin}" upper="${joint5_PositionMax}"/>
    </joint>

    <xacro:motorTransmission name="5"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_5_ft_sensor_topic</topicName>
        <jointName>z1_joint_5</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_5">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/manipulator/z1_Link05.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <inertial>
            <origin rpy="0 0 0" xyz="${L05_ComX} ${L05_ComY} ${L05_ComZ}"/>
            <mass value="${L05_Mass}"/>
            <inertia
                ixx="${L05_Ixx}" ixy="${L05_Ixy}" ixz="${L05_Ixz}"
                iyy="${L05_Iyy}" iyz="${L05_Iyz}"
                izz="${L05_Izz}"/>  
        </inertial>
    </link>

    <joint name="z1_joint_6" type="revolute">
        <origin rpy="0 0 0" xyz="0.0492 0.0 0.0"/>
        <parent link="z1_link_5"/>
        <child link="z1_link_6"/>
        <axis xyz="1 0 0"/>
        <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
        <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${joint6_PositionMin}" upper="${joint6_PositionMax}"/>
    </joint>

    <xacro:motorTransmission name="6"/>
    <gazebo>
        <plugin filename="libgazebo_ros_ft_sensor.so" name="ft_sensor">
        <updateRate>30.0</updateRate>
        <topicName>z1_joint_6_ft_sensor_topic</topicName>
        <jointName>z1_joint_6</jointName>
        </plugin>
    </gazebo>

    <link name="z1_link_6">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://qm_description/meshes/manipulator/z1_Link06.stl" scale="1 1 1"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${motor_height}" radius="${motor_diameter}"/>
            </geometry>
            <origin rpy="0 ${PI/2.0} 0" xyz="${motor_height/2.0} 0 0"/>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${L06_ComX} ${L06_ComY} ${L06_ComZ}"/>
            <mass value="${L06_Mass}"/>
            <inertia
                ixx="${L06_Ixx}" ixy="${L06_Ixy}" ixz="${L06_Ixz}"
                iyy="${L06_Iyy}" iyz="${L06_Iyz}"
                izz="${L06_Izz}"/> 
        </inertial>
    </link>

    <joint name="z1_camera_1" type="fixed">
        <origin rpy="${PI/2.0} ${PI/2.0} 0" xyz="0.015 0.0 0.0"/>
        <parent link="z1_link_6"/>
        <child link="camera_support_1"/>
    </joint>

    <link name="camera_support_1">
        <visual>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_1.stl" scale="1 1 1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_1.stl" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <inertial>
            <origin xyz="0.01228796808 0.01249999995 0.00005455685"/>
            <mass value="0.00312302"/>
            <inertia ixx="0.00000189979018" ixy="0.00000000" ixz="0.00000000188660" iyy="0.00000204231304" iyz="0.00000000" izz="0.00000045513762"/> 
        </inertial>
    </link>

    <joint name="z1_camera_2" type="fixed">
        <origin rpy="0 ${PI} 0" xyz="0.0 0.0 0.0"/>
        <parent link="camera_support_1"/>
        <child link="camera_support_2"/>
    </joint>

    <link name="camera_support_2">
        <visual>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <inertial>
            <origin xyz="0.02606678445 0.01310900418 0.00003986439"/>
            <mass value="0.00582375"/>
            <inertia ixx="0.00000336210388" ixy="-0.00000006511344" ixz="0.00000000535896" iyy="0.00000529075409" iyz="-0.00000000000178" izz="0.00000244065878"/>
        </inertial>
    </link>

    <joint name="z1_camera_3" type="fixed">
        <origin rpy="${85*PI/180} ${PI/2.0} 0" xyz="0.0825 0.0246 0.04"/>
        <parent link="camera_support_2"/>
        <child link="camera_support_3"/>
    </joint>

    <link name="camera_support_3">
        <visual>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/support_3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <inertial>
            <origin xyz="0.04000010933 -0.00463324120 0.00719944346"/>
            <mass value="0.00438996"/>
            <inertia ixx="0.00000100637191" ixy="0.00000000" ixz="0.00000000" iyy="0.00000178536815" iyz="0.00000006806630" izz="0.00000264518318"/>
        </inertial>
    </link>

    <joint name="z1_camera_4" type="fixed">
        <origin rpy="0 ${PI} 0" xyz="0.04 0.013 -0.012"/>
        <parent link="camera_support_3"/>
        <child link="camera"/>
    </joint>

    <link name="camera">
        <visual>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/camera.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/camera.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <inertial>
            <origin xyz="-0.03237073405 -0.00068389542 -0.00575253731"/>
            <mass value="0.07000000"/>
            <inertia ixx="0.00000497837376" ixy="-0.00000003261441" ixz="-0.00000000155222" iyy="0.00010466042609" iyz="-0.00000046967192" izz="0.00010658952406"/>
        </inertial>
    </link>

    <joint name="z1_camera_5" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="camera"/>
        <child link="camera_cover"/>
    </joint>

    <link name="camera_cover">
        <visual>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/camera_cover.stl" scale="1 1 1"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://qm_description/meshes/camera/camera_cover.stl" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <inertial>
            <origin xyz="-0.01251900 -0.00004375 -0.00505609"/>
            <mass value="0.00500000"/>
            <inertia ixx="0.00000048" ixy="0.00000000" ixz="-0.00000000" iyy="0.00000921" iyz="-0.00000000" izz="0.00000945"/>
        </inertial>
    </link>
 
    <xacro:if value="$(arg UnitreeGripper)" >
        <joint name="gripperStator" type="fixed">
            <origin rpy="0 0 0" xyz="0.051 0.0 0.0"/>
            <parent link="z1_link_6"/>
            <child link="gripperStator"/>
        </joint>

        <link name="gripperStator">
            <visual>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/z1_GripperStator.stl" scale="1 1 1"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/z1_GripperStator.stl" scale="1 1 1"/>
                </geometry>
                <material name="green"/>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${GripperStator_ComX} ${GripperStator_ComY} ${GripperStator_ComZ}"/>
                <mass value="${GripperStator_Mass}"/>
                <inertia
                    ixx="${GripperStator_Ixx}" ixy="${GripperStator_Ixy}" ixz="${GripperStator_Ixz}"
                    iyy="${GripperStator_Iyy}" iyz="${GripperStator_Iyz}"
                    izz="${GripperStator_Izz}"/> 
            </inertial>
        </link>

        <joint name="z1_handle_grip" type="fixed">
            <origin rpy="${-PI/2} 0 0" xyz="0.09 0.0 -0.008"/>
            <parent link="gripperStator"/>
            <child link="handleGrip"/>
        </joint>
    
        <link name="handleGrip">
            <visual>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/handlegrip.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/handlegrip.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="green"/>
            </collision>
         </link>

        <!-- TODO Change to revolute once controller is programmed -->
        <joint name="z1_joint_Gripper" type="fixed"> 
            <origin rpy="0 0 0" xyz="0.049 0.0 0"/>
            <parent link="gripperStator"/>
            <child link="gripperMover"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${jointDamping}" friction="${jointFriction}"/>
            <limit effort="${torqueMax}" velocity="${velocityMax}" lower="${Gripper_PositionMin}" upper="${Gripper_PositionMax}"/>
        </joint>

        <!-- <transmission name="z1_joint_Gripper_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="z1_joint_Gripper">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="z1_joint_Gripper_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission> -->

        <!-- <gazebo>
            <plugin name="gripper_position_controller" filename="libgazebo_ros_control_select_joints.so">
                <robotNamespace>/</robotNamespace>
                <joints>z1_joint_Gripper</joints>
            </plugin>
        </gazebo> -->

        <link name="gripperMover">
            <visual>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/z1_GripperMover.stl" scale="1 1 1"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://qm_description/meshes/manipulator/z1_GripperMover.stl" scale="1 1 1"/>
                </geometry>
                <material name="green"/>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${GripperMover_ComX} ${GripperMover_ComY} ${GripperMover_ComZ}"/>
                <mass value="${GripperMover_Mass}"/>
                <inertia
                    ixx="${GripperMover_Ixx}" ixy="${GripperMover_Ixy}" ixz="${GripperMover_Ixz}"
                    iyy="${GripperMover_Iyy}" iyz="${GripperMover_Iyz}"
                    izz="${GripperMover_Izz}"/> 
            </inertial>
        </link>

        <link name="z1_end_effector">
            <!-- <visual>
                <geometry>
                    <sphere radius="0.01"/>
                </geometry>
                <material name="red"/>
            </visual> -->
            <!-- <inertial>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
            <collision>
                <geometry>
                    <sphere radius="0.01"/>
                </geometry>
                <surface>
                    <contact>
                        <collide_bitmask>0</collide_bitmask>
                    </contact>
                </surface>
            </collision> -->
        </link>

        <joint name="z1_joint_end_effector" type="fixed">
            <origin xyz="0.19 0 -0.025" rpy="0 0 0"/>
            <parent link="gripperStator"/>
            <child link="z1_end_effector"/>
        </joint>

    </xacro:if>

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libqm_hw_sim.so">
            <robotNamespace>/</robotNamespace>
            <robotParam>qm_description</robotParam>
            <robotSimType>qm_gazebo/QMHWSim</robotSimType>
        </plugin>
    </gazebo>

</robot>
