# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# -----------------------Z1------------------------------------

gripper_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_Gripper
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint01_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_1
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint02_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_2
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint03_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_3
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint04_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_4
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint05_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_5
    pid: {p: 300.0, i: 0.0, d: 5.0}

Joint06_controller:
    type: effort_controllers/JointPositionController
    joint: z1_joint_6
    pid: {p: 300.0, i: 0.0, d: 5.0}